development:
  clients:
    default:
      database: store_with_mongo_development
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: store_with_mongo_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: store_with_mongo_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
